import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { createImageProvider } from './images';

/**
 * Capas v2: cenas fotorrealistas por categoria (4 variações), no lugar das ilustrações abstratas.
 * Gera em uma pasta local (staging) para revisão; "apply" envia ao pool do storage depois da aprovação.
 * Uso: tsx src/editorial/covers-v2.ts gen <pasta>   |   tsx src/editorial/covers-v2.ts apply <pasta>
 */
const STYLE = 'Photorealistic editorial news photograph, cinematic lighting, shallow depth of field, rich deep blue and teal color grading, high detail, professional magazine quality. No text, no logos, no watermarks, no readable letters, no recognizable faces.';

export const SCENES: Record<string, string[]> = {
  'modelos-de-ia': ['rows of glowing GPU servers in a dark data center aisle', 'close-up of a glowing computer chip circuit board with blue light', 'engineer silhouette in front of large screens showing abstract neural network visualizations', 'futuristic server hall with blue light streaks and cooling pipes', "a researcher looking at a wall of glowing data charts in a dark control room, seen from behind", "macro of fiber optic cables with glowing blue light", "a supercomputer cabinet with blue LED lights, low angle", "abstract glowing particles forming a brain-like shape in dark space", "a developer at night with several monitors of plain code, blue ambient light", "cooling system pipes and servers in a clean data center, wide angle", "a glowing processor on a motherboard with soft bokeh", "long exposure of light trails through a server corridor"],
  'open-source': ['hands typing code on a laptop in a dim workspace with colorful syntax on screen', 'developers collaborating around a table with laptops in a bright modern loft', 'macro of a mechanical keyboard with soft blue backlight', 'laptop with code on screen beside a coffee cup at night', "a group of developers high-fiving after a release in a bright office, seen from the side", "a laptop on a wooden table by a window with a plant, code on screen", "a hand-drawn network diagram on a glass wall with markers", "a developer working with headphones in a cozy night room, code on a monitor", "a team meeting around a large screen in a loft, seen from behind", "open laptop in a cafe with city lights bokeh", "a stack of plain laptops and cables on a workbench", "hands typing on a keyboard with code reflected on glasses"],
  agentes: ['a sleek humanoid robot assistant at a modern office desk', 'a small friendly robot helping a person at a laptop, bright office', 'holographic interface floating above a desk in a dark room, blue glow', 'robot hand and human hand reaching toward each other over a keyboard', "a robot arm handing a coffee to a person in a bright modern office kitchen", "a glowing blue assistant orb floating above a desk, dark room", "a white humanoid robot standing in front of a large window with city view", "a person talking to a small desktop robot, warm light", "a robot hand holding a smartphone, close-up", "automated warehouse with small robots moving boxes, blue light", "a tablet showing an abstract blue interface held by a robot hand", "a robot and a human looking together at a screen, seen from behind"],
  imagem: ['a digital artist drawing on a graphics tablet with colorful artwork on a monitor', 'a camera lens with colorful light reflections close-up', 'a creative studio with large monitors showing vivid generated artwork', 'abstract colorful light painting in a dark studio', "a photographer editing portraits on a monitor in a dim studio", "a paint-splashed canvas with vivid colors in a bright atelier", "a designer holding a stylus over a tablet with colorful gradients", "a prism splitting light into a rainbow on a dark background", "a creative desk with sketches, color swatches and a monitor with a landscape", "long exposure neon light painting of swirling lines", "a camera on a gimbal capturing a sunset city", "a gallery wall with abstract artworks in soft light"],
  video: ['a professional video editing suite with timelines on large monitors', 'a cinema camera on a tripod in a studio with soft lights', 'film clapperboard and studio lights, cinematic dark background', 'video production control room with many screens', "a film set with large soft lights and a camera dolly, cinematic", "a person editing video on a laptop with a timeline, dim room", "a studio green screen with a camera and lights", "a drone flying over a city at sunrise", "a cinema screen seen from the audience in a dark theater, blue glow", "film reels and a vintage camera on a table, moody light", "a director chair and spotlights on an empty stage", "a streaming setup with ring light and camera in a home studio"],
  audio: ['studio microphone with warm light in a recording booth', 'headphones on a mixing console in a dim studio', 'abstract sound waveform glowing on a dark screen', 'musician producer at a mixing desk with soft blue light', "vinyl record spinning on a turntable with warm blue light", "a podcast studio with two microphones and soft lighting", "a guitar and an amplifier in a dim music room", "hands adjusting knobs on an audio synthesizer", "a singer silhouette at a microphone with stage lights", "a pair of studio monitor speakers in a dark room", "a spectrum analyzer with glowing blue bars on a dark screen", "a concert crowd silhouette with stage lights"],
  robotica: ['an industrial robot arm assembling parts in a clean modern factory', 'a humanoid robot walking in a bright laboratory', 'autonomous delivery robot on a city street at dusk', 'robotic arms on an automated production line, blue lighting', "a robotic dog walking on a city sidewalk at dusk", "an autonomous car on a rainy city street with light reflections", "a robot hand gently holding a small plant", "an engineer testing a humanoid robot in a lab", "a surgical robot in a clean operating room, blue light", "a drone delivering a package in front of a modern building", "robot arms painting a car body in a factory with light sparks", "a small wheeled robot in a bright warehouse aisle"],
  pesquisa: ['scientist in a white lab coat looking at holographic data in a modern laboratory', 'a university library with warm light and rows of books', 'close-up of a microscope in a bright lab', 'a researcher whiteboard full of equations in a modern office', "a scientist pipetting samples in a bright laboratory", "a telescope under a starry sky at night", "a student studying in a quiet library with warm lamp light", "glassware with blue liquid in a modern lab, close-up", "a research team discussing around a table with charts, seen from behind", "an abstract glowing molecular structure in blue", "a notebook with graphs and a pen on a desk, soft light", "a university building with large windows at sunset"],
  negocios: ['modern glass skyscrapers seen from below at golden hour', 'business people shaking hands in a bright boardroom, seen from behind', 'a boardroom with a city view and an empty long table', 'financial district skyline at dusk with light trails', "two executives walking in a modern glass lobby, seen from behind", "a meeting table with laptops and coffee, bright office with city view", "a business person looking over a city from a high office window, silhouette", "modern office tower reflections with blue sky", "a handshake in close-up in a bright office, no faces", "a conference room with a presentation screen, seen from behind", "a harbor with container ships and cranes at dawn", "an airport terminal with large windows at golden hour"],
  startups: ['a small team brainstorming around a table with sticky notes in a bright startup office', 'three young entrepreneurs standing and looking at a large wall screen in a modern office, seen from behind', 'a whiteboard with product sketches and sticky notes, creative office', 'two founders celebrating with a high five in a bright startup office, seen from the side', "a founder pitching to a small group in a bright room, seen from behind", "a garage workshop with prototypes and a laptop, warm light", "a team celebrating around a table, seen from the side, laptops with no logos", "a whiteboard covered in colorful sticky notes in a bright office", "a young entrepreneur working late at a desk with city lights behind", "a paper airplane flying in front of a sunrise sky", "a small bright office with plants, desks and a big window, empty", "a prototype device on a workbench with tools"],
  investimentos: ['a stock market trading screen with green and red charts glowing', 'stacks of coins with a rising arrow chart in the background, soft light', 'trading floor monitors showing candlestick charts at night', 'aerial view of a glass financial district at blue hour, windows without signage', "gold bars stacked in a vault with soft light", "a trader silhouette in front of multiple glowing screens", "a hand placing a coin on a stack, shallow depth of field", "skyscrapers of a financial district with golden hour reflections", "a small plant growing from a stack of coins, soft light", "green candlestick chart glowing on a dark monitor, close-up", "a calculator and charts on a desk with warm light", "a bull statue in a financial district at dusk"],
  ferramentas: ['a modern desk with laptop, tablet and phone showing app interfaces, top view', 'a sleek workspace with a laptop and a smartphone on a wooden desk, bright', 'hands holding a smartphone with a glowing abstract app interface', 'a tidy digital workspace with multiple screens and plants', "a smartphone and a smartwatch on a desk with soft blue glow", "a designer desk with a tablet and stylus, top view, bright", "a laptop showing abstract dashboard charts, side view, dark room", "hands using a tablet with a glowing abstract interface", "a minimal desk setup with a monitor, keyboard and lamp at night", "a person using a laptop in a bright cafe, seen from the side", "a smart speaker on a shelf with soft light", "wireless earbuds and a phone on a wooden table, macro"],
  legislacao: ['a courtroom with a wooden gavel and scales of justice in warm light', 'a modern parliament building facade at dusk', 'law books and a gavel on a polished desk, dramatic light', 'columns of a classical government building with blue sky', "a statue of Lady Justice against a blue sky", "a judge bench in an empty courtroom with warm light", "a pen signing a document on a polished desk, close-up", "the Brazilian National Congress building at dusk with blue sky", "a stack of legal books on a wooden table in a library", "a symmetrical marble corridor of a government building", "hands holding a gavel over a sound block, shallow depth of field", "a classical courthouse facade with stairs in morning light"],
  'ia-no-brasil': ['aerial view of the São Paulo skyline at sunset', 'Rio de Janeiro bay and mountains at golden hour, aerial view', 'Brasília modernist architecture at dusk with deep blue sky', 'busy Avenida Paulista at night with light trails', "aerial view of Copacabana beach at sunrise", "Sugarloaf mountain and Guanabara Bay at dusk", "Sao Paulo skyline at night with light trails on avenues", "Brasilia cathedral with its curved concrete columns under blue sky", "the Amazon rainforest from above with morning mist", "Ibirapuera park lake with skyscrapers behind at golden hour", "a modern Brazilian city skyline at blue hour", "a colorful Brazilian city street with modern buildings in daylight"],
  geral: ['abstract glowing neural network of light points on a dark blue background, depth of field', 'a modern futuristic city skyline with digital light overlays at night', 'glowing blue circuit lines forming a world map on dark background', 'a person silhouette looking at a large wall of data visualizations', "glowing blue data streams flowing through a dark abstract tunnel", "a lone person looking at a futuristic city skyline from a rooftop at night, silhouette", "a glowing globe of connected points over dark blue background", "abstract blue light waves with soft bokeh, depth of field", "a futuristic control room with blue holographic panels, seen from behind", "a close-up of a glowing lens reflecting blue light", "a modern corridor with blue light panels and perspective lines", "digital rain of blue light particles on dark background"],
};

async function main() {
  const [mode, dir] = process.argv.slice(2);
  if (!dir) throw new Error('informe a pasta');
  if (mode === 'gen') {
    const provider = createImageProvider();
    if (!provider) throw new Error('sem provedor de imagem');
    for (const [slug, scenes] of Object.entries(SCENES)) {
      for (let i = 0; i < scenes.length; i++) {
        const file = join(dir, slug, `${i}.png`);
        if (existsSync(file)) continue;
        try {
          const bytes = await provider.generate(`${scenes[i]}. ${STYLE}`);
          mkdirSync(dirname(file), { recursive: true });
          writeFileSync(file, bytes);
          console.log('ok', slug, i);
        } catch (e) {
          console.log('PARADO', slug, i, String(e instanceof Error ? e.message : e).slice(0, 200));
          return;
        }
      }
    }
    console.log('TUDO GERADO');
  }
  if (mode === 'apply') {
    const { createServiceClient } = await import('@/lib/supabase/clients');
    const { readFileSync } = await import('fs');
    const db = createServiceClient();
    let n = 0;
    for (const [slug, scenes] of Object.entries(SCENES)) {
      for (let i = 0; i < scenes.length; i++) {
        const bytes = readFileSync(join(dir, slug, `${i}.png`));
        const up = await db.storage.from('article-covers').upload(`categories/${slug}/${i}.png`, bytes, { contentType: 'image/png', upsert: true, cacheControl: '300' });
        if (up.error) throw up.error;
        n++;
      }
    }
    console.log('aplicadas', n);
  }
}
main().catch((e) => { console.error(e); process.exit(1); });
